### ISSUE TITLE
生成多个函数定义时报错

### ISSUE THREAD

**Issue by mrw954** [Kohirus/cppassist.nvim#1]
Error loading lua [string ":lua"]:1: '=' expected near '<eof>'

![image](https://user-images.githubusercontent.com/24312113/219787300-cef3ebec-9748-43f8-8c42-30b96471d327.png)

**Comment by Kohirus** [comment]
选择单个函数生成定义时会报错吗？

**Comment by mrw954** [comment]
单个函数不会呢，

**Comment by mrw954** [comment]
之前用过https://github.com/chxuan/cpp-mode 插件，和这个插件功能类似。不过是vim script实现的。

**Comment by Kohirus** [comment]
我这边测试没有什么问题，你可以录个视频

**Comment by mrw954** [comment]
> 我这边测试没有什么问题，你可以录个视频

是我配置的原因，不知道为什么， opts = {buffer = nil, silent = true, noremap = true, nowait = false,}没有生效，
我将keymap 改为下面的配置后成功生成多个函数了。
'<Cmd>lua require("cppassist").ImplementInSourceInVisualMode { noremap = true, silent = true }<CR>',
